### ISSUE TITLE
Resizing window does not resize background

### ISSUE THREAD

**Issue by AustinHellerRepo** [kaphula/winit-egui-wgpu-template#1]
When trying to resize the window the black background maintains the same size. I am trying to debug the issue myself, but I haven't yet succeeded, so I figured that I'd submit this issue in the meantime while I continue to figure out what's wrong.

**Comment by kaphula** [comment]
Can you be more specific what is exactly the issue? Nothing is being drawn on the background so I don't understand how resizing can be even observed. I modified the example to show how pixels per scaling can be adjusted so that the **egui** window size can be resized.

**Comment by AustinHellerRepo** [comment]
Sorry for the lack of details. I have provided screenshots below of the result when I resize the window to be slightly smaller and slightly larger than the original size. It leaves the black background the same size. If I resize to be larger than the initial window size, there is a gap that appears to let me see through the window.
![image](https://github.com/kaphula/winit-egui-wgpu-template/assets/25905456/cbe55d24-b6d7-40b0-85e2-66f87933c503)
![image](https://github.com/kaphula/winit-egui-wgpu-template/assets/25905456/8e33ecee-ac76-46a7-97fb-31fd205f19c4)

**Comment by kaphula** [comment]
I see. What OS are you running? I pushed a new commit that resizes the surface when window resize event happens, please try that and see what happens. I _think_ this should fix the issue.

**Comment by AustinHellerRepo** [comment]
That fixed it! Thanks!
I'm running Ubuntu 22.04.4 LTS btw.
