### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by POPOBE97** [kaphula/winit-egui-wgpu-template#2]
```
thread 'main' panicked at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.19.4/src/instance.rs:521:39:
called `Option::unwrap()` on a `None` value
```

Environment: Macbookpro M3pro

**Comment by kaphula** [comment]
Can you test if changing [this](https://github.com/kaphula/winit-egui-wgpu-template/blob/master/src/main.rs#L28) to this:
```rust
    let instance = wgpu::Instance::new(InstanceDescriptor::default());
```
helps. I don't have a mac to test.

**Comment by POPOBE97** [comment]
> Can you test if changing [this](https://github.com/kaphula/winit-egui-wgpu-template/blob/master/src/main.rs#L28) to this:
> 
> ```rust
>     let instance = wgpu::Instance::new(InstanceDescriptor::default());
> ```
> 
> helps. I don't have a mac to test.

After I applied your change, the demo run as expected. Thank you for the help! ;)

This is a clean and great demo.
