### ISSUE TITLE
How to use multi-touch?

### ISSUE THREAD

**Issue by oUp2Uo** [kaphula/winit-egui-wgpu-template#3]
Hi, thanks for the sample code.

I am a newbie to rust and wgpu.
I tried to use multi-touch, which has the gesture, and easier using than touch, I thought.
But I could not find a event for multi-touch in `WindowEvent`, only `WindowEvent::Touch`.

Do you have any idea about this?

Thank you.

**Comment by kaphula** [comment]
Hi, I think you need to consult [winit](https://github.com/rust-windowing/winit) for that information since this repository is focused only on showing how to glue together winit, egui and wgpu.

**Comment by oUp2Uo** [comment]
> Hi, I think you need to consult [winit](https://github.com/rust-windowing/winit) for that information since this repository is focused only on showing how to glue together winit, egui and wgpu.

Thanks for the replay.
I found the you write `WindowEvent::Touch` in the program, and thought maybe you know about the event.
I will try to search for more information.

Thanks again.

**Comment by kaphula** [comment]
I have no experience with the touch stuff, sorry.
