### ISSUE TITLE
Any text not showing correclty

### ISSUE THREAD

**Issue by eihabmuhur** [kaphula/winit-egui-wgpu-template#6]
Any text that does not appear correctly as shown in the image

![Screenshot 2024-10-19 at 7 32 42 PM](https://github.com/user-attachments/assets/706687dc-dd6a-48ad-88b0-4704d47f5db2)

**Comment by kaphula** [comment]
Weird stuff mate. Which version of Windows are you running?

**Comment by eihabmuhur** [comment]
Windows 10 as vmware

The code didn't work until added this:

let mut limits = wgpu::Limits::downlevel_webgl2_defaults();
limits.max_texture_dimension_1d = 4096;
limits.max_texture_dimension_2d = 4096; 

Does it have an effect?

**Comment by kaphula** [comment]
You should probably be fine just using the `downlevel_defaults()` like this:
 
```rust
        let (device, queue) = adapter
            .request_device(
                &wgpu::DeviceDescriptor {
                    label: None,
                    required_features: features,
                    required_limits: wgpu::Limits::downlevel_defaults(),  // <-
                    memory_hints: Default::default(),
                },
                None,
            )
            .await
            .expect("Failed to create device");
```
They ensure wider range of older hardware support with more strict limits. I can patch the example to use these lower limits by default at some point or you can make a PR for the change if you want.

**Comment by eihabmuhur** [comment]
On a real Windows it works fine even the above method.
Maybe I should use real Windows.
I'm using a virtual Windows on a Mac now.

Thanks
